// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpqwofqzoavlipmnltpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwcXdvZnF6b2F2bGlwbW5sdHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDI3ODgsImV4cCI6MjA2NDAxODc4OH0.ipe7iH8NZ7swdrUTsZaQJDHGFyH0retiI2e8bZasTGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);